export const Errors = {
    'INVALID_PASSWORD': 'INVALID_PASSWORD',
    'INVALID_EMAIL': 'INVALID_EMAIL',
    'NULL_OR_UNDEFINED': 'NULL_OR_UNDEFINED',
    'EMPTY': 'EMPTY',
    'INVALID_LESS_THAN': 'INVALID_LESS_THAN',
    'INVALID_GREATER_THAN': 'INVALID_GREATER_THAN',
    'EMPTY_NAME': 'EMPTY_NAME',
    'BIG_NAME': 'BIG_NAME',
    'SMALL_NAME': 'SMALL_NAME',
    'NAME_WITHOUT_LAST_NAME': 'NAME_WITHOUT_LAST_NAME',
    'NAME_WITH_INVALID_CHARACTERS': 'NAME_WITH_INVALID_CHARACTERS',
    'INVALID_UUID': 'INVALID_UUID',
    'INVALID_CPF': 'INVALID_CPF'
} as const
